// src/components/catalog.js
const catalog = [
  {
    id: 1,
    name: 'Yerba Mate 1kg',
    price: 2500,
    image: '/images/images_catalog/yerbamate.jpg',
    description: 'Yerba mate de alta calidad con 1 kg de contenido. Ideal para preparar mate con un sabor intenso y duradero. Deja una agradable sensación en boca con un toque ligeramente amargo.',
    weight: '1 kg',
    flavor: 'Amargo',
  },
  {
    id: 2,
    name: 'Bombilla de Acero',
    price: 1200,
    image: '/images/images_catalog/bombillaacero.jpg',
    description: 'Bombilla de acero inoxidable de alta resistencia. Perfecta para disfrutar de tu mate sin alterar el sabor. Diseño elegante y funcional que asegura una experiencia de mate perfecta.',
    material: 'Acero inoxidable',
    length: '20 cm',
  },
  {
    id: 3,
    name: 'Mate de Madera',
    price: 4000,
    image: '/images/images_catalog/MateMadera.jpg',
    description: 'Mate de madera tallado a mano con acabados finos. Ofrece una experiencia tradicional con un sabor auténtico. Ideal para aquellos que aprecian la artesanía y la elegancia natural.',
    material: 'Madera',
    capacity: '250 ml',
  },
  {
    id: 4,
    name: 'Yerba Mate Orgánica',
    price: 3000,
    image: '/images/images_catalog/YerbaMateOrgánica.jpg',
    description: 'Yerba mate orgánica cultivada sin pesticidas ni químicos. Ofrece un sabor suave y natural, con notas herbales frescas. Perfecta para los amantes de productos ecológicos.',
    weight: '500 g',
    flavor: 'Suave',
  },
  {
    id: 5,
    name: 'Kit de Mate Completo',
    price: 7000,
    image: '/images/images_catalog/KitMateCompleto.jpg',
    description: 'Kit completo para preparar y disfrutar del mate. Incluye un mate de cerámica, bombilla de acero y yerba mate. Todo lo que necesitas para empezar tu experiencia de mate.',
    contents: 'Mate de cerámica, bombilla de acero, 500 g de yerba mate',
  },
  {
    id: 6,
    name: 'Yerba Mate con Sabor',
    price: 2700,
    image: '/images/images_catalog/YerbaMateabor.jpg',
    description: 'Yerba mate con sabor a frutos rojos, ideal para quienes buscan una experiencia más dulce y afrutada. Aporta un toque distintivo a tu mate.',
    weight: '500 g',
    flavor: 'Frutos rojos',
  },
  {
    id: 7,
    name: 'Bombilla Tradicional',
    price: 1500,
    image: '/images/images_catalog/BombillaTradicional.jpg',
    description: 'Bombilla tradicional de acero inoxidable, perfecta para disfrutar de tu mate con comodidad. Diseño clásico y duradero que mantiene la calidad de tu bebida.',
    material: 'Acero inoxidable',
    length: '18 cm',
  },
  {
    id: 8,
    name: 'Mate de Cerámica',
    price: 4500,
    image: '/images/images_catalog/MateCerámica.jpeg',
    description: 'Mate de cerámica pintado a mano, con detalles artísticos que lo hacen único. Ofrece una experiencia de mate suave y equilibrada, ideal para cualquier ocasión.',
    material: 'Cerámica',
    capacity: '300 ml',
  },
  {
    id: 9,
    name: 'Yerba Mate de Campo',
    price: 2800,
    image: '/images/images_catalog/YerbaMateCampo.jpg',
    description: 'Yerba mate tradicional de campo, con un sabor robusto y auténtico. Perfecta para quienes buscan un toque más fuerte en su mate.',
    weight: '500 g',
    flavor: 'Robusto',
  },
  {
    id: 10,
    name: 'Mate Imperial',
    price: 3500,
    image: '/images/images_catalog/MateImperial.jpg',
    description: 'Mate de acero inoxidable con un diseño elegante y moderno. Ideal para mantener la temperatura de tu mate durante más tiempo. Aporta un toque de sofisticación a tu ritual del mate.',
    material: 'Acero inoxidable',
    capacity: '350 ml',
  },
];

export default catalog;
